# This file was created following this tutorial: https://medium.com/@jharvey1012/a-beginners-guide-to-creating-a-containerized-web-application-development-environment-with-docker-e903169004ff

FROM alpine:latest

RUN apk update
RUN apk add nodejs
RUN apk add nodejs npm
RUN node -v

# this command below is equivalent to the lines above
# FROM node:latest
